### PR TITLE
Added gitignore

### PR DESCRIPTION
**Pull request by patrick91**

### CODE REVIEW

**Comment by sylnsfar** [comment]
Thank you, this thing will help a lot.

**Comment by patrick91** [comment]
You're welcome, I'm working on a installable (via pip) version here: https://github.com/patrick91/qrcode/tree/structure

Not sure if I'll be able to make a pr (I did too many changes), but let me know if you're interested

**Comment by sylnsfar** [comment]
But this one is installable via pip already. Do you mean a importable version?

**Comment by patrick91** [comment]
Yes, sorry :)

**Comment by sylnsfar** [comment]
I have also thought about that and been recoding these days. It will be finished soon.

**Comment by patrick91** [comment]
Awesome!

Can you also add a way to specify the output filename? :)

**Comment by sylnsfar** [comment]
I updated just now and hope you like it.

**Comment by patrick91** [comment]
Amazing! Thank you very much :)

**Pull request merged**
